### ISSUE TITLE
Two Issues

### ISSUE THREAD

**Issue by armchairrockstar1** [TheLinuxITGuy/Turtle-Dragonflight#6] opened 2024-06-20 21:40 UTC
Thanks for the project. I've found two issues:

1. Quest tracker doesn't work
2. Quest progress updates on the middle of the screen don't appear, such as 1/12 apple. This applies to error messages as well, such as "You don't have enough energy" etc.

**Comment by alchem1ster** [comment] 2024-07-07 21:25
Comment out this line inside `\tDF\tReduced-actionbar.lua`:

![image](https://github.com/TheLinuxITGuy/Turtle-Dragonflight/assets/3815426/2a60bae5-e637-4795-bbfd-c7810bbb7c4f)

**Comment by TheLinuxITGuy** [comment] 2024-07-11 13:03
Thanks @alchem1ster . @armchairrockstar1  - did that work for you for #2? #1 is by design. pfQuest + pfQuest turtle are typically used. The default quest tracker was removed to provide a cleaner look.

**Comment by TheLinuxITGuy** [comment] 2024-07-12 22:22
1 - Not sure where the original quest tracker has gone. I disabled my addon and it's still missing. Even on a new character.
2 - Fixed in v1.8.6

**Closed by TheLinuxITGuy** 2024-07-12 22:22 UTC
